dist: bionic
addons:
  apt:
    source:
    - docker-bionic
    packages:
    - docker
services:
- docker
env:
  global:
  - PROJECT: tokend
  - IMAGE_NAME: stellar-withdraw-svc
  - secure: H1vBFW4jm1rFSIgeYhnkim0i1V+PZNtck94gFtmcrhEjfjTJ4U9qn9g4AJfnAA+ZRWDZAJ2h9ExkSGCYjkFrxir5c0A3CgGrW3vIoZLo+/q6VUrgBXAjqpYLcM+2thP6xZdiSB0rJPO5S5uTPYg6dgNmT8tMjmXmHnV0Db5kqMZK+HFPTx38jE0nLvyAC+3AQBHEMGJ1a/iGqfT05qaf6knIdDhDwPaBVrs21hJCaQGn2VNTl+thAIagwekJ8gtD3aCmEEVpKo/paWsNW1OPGFUY14NvuScPCYruy8RI7NLIda47cF3xHBPrYmVXg/9FxaC4/KGPk4vbwGu9AlRWzAdvIhAtxdEkDGpLvKWse1q90Nu2gdIRuE7djULZda6VfxbFvEIA2scHXrN/owUWu8eS6BQa6d8HDuT9i3ljAzXR8QVJQ+FsobSwxdXlRkxjHjxMDtBd+TkqL7UYGlKpRN6M3iOtKea/DNSZbhgEYzyJTnFhMV5khfLwTZry1cZ7vzMRk3dgXEj9xbGY1PUnNC6WpQF8F27wEjHy3iR0KrQG3uXEBY8iAaLsKcMV+QaILEfjqSPbQKs7CupS2EGMF8uCmL9xAj+sDPQuVzYBicAjpt477/HJ7LsaxQdTSK/AQYd9Qdr2pYJeWFnXfPxu0BdPl8V+1rq19afeoFsef4k=
  - secure: fG4WhhaBRKFFTgsM/ltVJGfBU+R827Dm+ssy0hP5moWK4Flc/uhuGktG2NMcjYuuWqg1ATh/gaSavbGnW/6wa7/t6ApTtRXwAnXXmSBdO3f1u78fpdyiPG2pYCCYQHUyNqR63UGUZNytfAuur4Kt7EBqXl7cpMqAXvIv9OzCDYJzUbdzyMv/t4XyhmizbuFRdPHrYKUYJhKnvZdx5iGLSw8nOXsFy8b9UOz/YY9JNxFG64x44dyh0EoGvnRMyYm1Yhoa7eEE07Z0Var/j1V+1qhMmRGTBK6NwcDzbU2z3wCenC1Mj199H2hULs7sb51K2uZWXSWUXtqrcXYRz1TonuIi/0b/5wVbyJQoO9iUxPPaFH36jA3wJpIULPHckD6+SGJyyslsKUkQN3zNu7vUT3O+R/W7HGRtGhfZYewdjwDwvlIjJjiDQxiAi0bQExM1XFWBz3j3aJN/xdHt/vMPft7J20dILkDRyYCt844hFgGOPJQZk7zURp2eOAR5+Do2DIatQs8Gl8uVsTwEiHyoNoUb53ACvRRYJ48JTjeJY5KZD9DwaUJfr4no0ATIENDmZML7fmjH4M6Yl3v37HCM4Fnth7YBn4YEWzKrYhfJYWZzp3Q8jpW9eW4/Eo/fRsnfa0k9QqjClmJo2foIWXcUP3mKcD2WF8735T8oHHYqADY=
  - secure: K77L+So8NZ2yRMWZ1+yS7icZpgFPRNWDQWKwNkb3CH++w3ZIsD6qQUQBz+ja+Bq/B2LoRToDGoGVkVVKSsynCx5stlTR1y1TE3lnPwpSYbQliHxNZFobjhlnNL/6/6zmgRmR8abUozckb7RVfqM+jCX06V5XtbGXUACwvZPMr5EgAFiAExLYHWXGLYfzFVhZImaYYPWpJ5l5CsbQOq1eSZDWctl/wXXO6CaGAtcXlWwlNiujKBxQicJcjeb8rjnDm1l2FqteAIMkEfCwDQGPxSRnqctCvQSCb7JKr+KCnEqrM0Xm/zNXiQ90LS9fnKN04Jq2r94ZaKSQ+H8MnejPVRvJV4ceKB6atC5yFZt8qlwKi32VXgjJ7HKMgCdL19VuFaaabCfwBYkO8X8J/fg0SLO4dEgD3PSRtV5w4HAmAjIMTGegMFJrMkZU8jPwwZ0MXve4VhDlPpcvsG6hO2VN+e+92z1T4FYws/WCGFrHP/p6zN4kiTb2p6/jtjDNYJ/qsRo62DThT2RFb7r+aUmJkQsXajrsBScOBJE5VCNTXExIq151L5uPtYjsa0uAFAckAd2vRHbgNtRzxF8WQ0nsjbeeUKxfHf5a3uXg8T/kQ+qrTghhnbuYPs0S4/+EwsJnsOSnLNCzfgpSLpOLLfu6IVkYm3IBXJOVEiW4JzjADmw=
  - secure: Wriymm6/ssa8pe6D73I8oA5zqvI2NritR3doTUhq+o1EuEsIc3PzCOlCQrUNyBQpED5h4cHc19Gjeb9c6fbB+twDbObEz3SLf6Bq0KtzASr/YKfX7atWHWpZKlRiloHU2OqPJ5+REgyj99MZTwIHd8Yi1IBLMpk8VdEbhBkypeL7rcXHN1l6mJ6k3O6Ls9bs9kVRVSn5T2A9NbG2f+Uz1gZcX2PWqCgXFN7PJjLSWb/Y9FWHiWghKr/hI18rsdkMyWsaBgI1zVcMV84/ieVS1pHUrvfFy4SV3XFv1KxlJ2RZ0czM4b5hbQ1QvOdDGIUM+DCap0WpYO4zSxC9BepdbpyWNr2BNSSk3JY92efS5pvtrf9gSVXuA0AcSvIx1J8BcmxmWvCfy8shIQb5ZVc/2sKQSBvPI2DQIn5Jv7ehoelPpF6fFbHvYrAPC6Pt6HllgYa2Sxe9t6+6ZMsqJhukqKc32VcLr8t9610TiBIPcCEAg1ffa0cSKnCHfHn5badmk3fWBHY3hH73I63YNAu0lHTD5Xj4sdGRD5lafQnDAiJkPM4kw4d9Q2LKez3RdV3sT1MbVuF3nPjoABq/90jvgIAW2Aup8lu18gMaxf/NIJG2QtxVp4b36jwgC/Piil95eVHkLpPJOxHDOnr9KtUSUFjkBVaNAx25H38FykS07rs=
script:
- export IMAGE_TAG=$(test -z $TRAVIS_TAG && echo $TRAVIS_COMMIT || echo $TRAVIS_TAG)
- docker build -t $PROJECT/$IMAGE_NAME:$IMAGE_TAG .
before_deploy:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - echo "$GITLABREG_PASSWORD" | docker login -u "$GITLABREG_USERNAME" --password-stdin registry.gitlab.com
  - docker tag $PROJECT/$IMAGE_NAME:$IMAGE_TAG registry.gitlab.com/$PROJECT/docker-registry/$IMAGE_NAME:$IMAGE_TAG
deploy:
- provider: script
  script:
  - docker push $PROJECT/$IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
    tags: true
- provider: script
  script:
  - docker push registry.gitlab.com/$PROJECT/docker-registry/$IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
    tags: false
